apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://kubernetes.github.io/ingress-nginx # Helm chart source
    chart: ingress-nginx
    targetRevision: 4.13.0 # match your current chart version
    helm:
      valueFiles:
      - $values/Helm-chart-yamls/ingress-nginx.yaml # reference to your Git repo values file
  - repoURL: https://github.com/SrivenkateswaraReddy/k3s-argocd-deployments.git # your Git repo with values.yaml
    targetRevision: feature/longhorn-gitops # Git branch
    ref: values # alias to use in valueFiles
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
