controller:
  image:
    repository: quay.io/metallb/controller
    tag: v0.15.2

speaker:
  image:
    repository: quay.io/metallb/speaker
    tag: v0.15.2

configInline:
  address-pools:
  - name: default
    protocol: layer2
    addresses:
    - 192.168.1.240-192.168.1.250
